### ISSUE TITLE
'IJKMediaFramework/IJKMediaFramework.h' file not found

### ISSUE THREAD

**Issue by devchena** [tsingsee/EasyPlayerPro-iOS#1]

**Comment by leo-09** [comment]
可以联系我，微信号18855117272，邮箱2779005381@qq.com------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;把子肉&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 晚上6:18
收件人:&nbsp;&quot;tsingsee/EasyPlayerPro-iOS&quot;<EasyPlayerPro-iOS@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tsingsee/EasyPlayerPro-iOS] &#39;IJKMediaFramework/IJKMediaFramework.h&#39; file not found (#1)

**Comment by leo-09** [comment]
可以联系我，微信号18855117272，邮箱2779005381@qq.com
